export const habitBase = [
  // --- Physical Activity & Movement ---
  {
    id: "cardio-workout",
    name: "30-min Cardio Workout",
    category: "exercise",
    weight: 4,
    emoji: "🏃‍♀️",
  },
  {
    id: "strength-training",
    name: "30-min Strength Training",
    category: "exercise",
    weight: 5,
    emoji: "💪",
  },
  {
    id: "evening-walk",
    name: "Walk 20 min After Dinner",
    category: "exercise",
    weight: 3,
    emoji: "🚶‍♀️",
  },
  {
    id: "morning-walk",
    name: "Early Morning Walk",
    category: "exercise",
    weight: 3,
    emoji: "🌅",
  },
  {
    id: "mobility-stretch",
    name: "10-min Mobility/Stretch",
    category: "mobility",
    weight: 2,
    emoji: "🤸",
  },
  {
    id: "posture-breaks",
    name: "Take Posture Breaks",
    category: "mobility",
    weight: 1,
    emoji: "🧘‍♀️",
  },
  {
    id: "take-the-stairs",
    name: "Take the Stairs",
    category: "exercise",
    weight: 1,
    emoji: "🚶🏻",
  },
  {
    id: "extra-steps",
    name: "Extra 5k Steps Day",
    category: "exercise",
    weight: 3,
    emoji: "👟",
  },

  // --- Nutrition & Hydration ---
  {
    id: "healthy-meal",
    name: "Cook a Home-Made Meal",
    category: "food",
    weight: 5,
    emoji: "🥗",
  },
  {
    id: "meal-prep",
    name: "Meal Prep Two Lunches",
    category: "food",
    weight: 4,
    emoji: "🍲",
  },
  {
    id: "fruit-dessert",
    name: "Enjoy a Fruit-Based Dessert",
    category: "food",
    weight: 1,
    emoji: "🍓",
  },
  {
    id: "drink-herbal-tea",
    name: "Drink Herbal Tea",
    category: "hydration",
    weight: 1,
    emoji: "🫖",
  },
  {
    id: "rehydrate-electrolytes",
    name: "Rehydrate with Electrolytes",
    category: "hydration",
    weight: 2,
    emoji: "💧",
  },
  {
    id: "carry-water-bottle",
    name: "Carry Reusable Water Bottle",
    category: "hydration",
    weight: 2,
    emoji: "🚰",
  },
  {
    id: "switch-to-unsweetened",
    name: "Switch to Unsweetened Tea/Coffee",
    category: "hydration",
    weight: 1,
    emoji: "☕️",
  },
  {
    id: "hydration-check",
    name: "2L Water Intake",
    category: "hydration",
    weight: 2,
    emoji: "💦",
  },

  // --- Sleep & Recovery ---
  {
    id: "full-sleep",
    name: "7+ Hours of Sleep",
    category: "sleep",
    weight: 5,
    emoji: "😴",
  },
  {
    id: "no-screens-before-bed",
    name: "No Screens 60 min Before Bed",
    category: "sleep",
    weight: 3,
    emoji: "📵",
  },
  {
    id: "early-sunlight",
    name: "Early Morning Sunlight",
    category: "sleep",
    weight: 2,
    emoji: "☀️",
  },
  {
    id: "evening-stretch",
    name: "Evening Stretch Routine",
    category: "recovery",
    weight: 2,
    emoji: "🧘",
  },
  {
    id: "cold-shower",
    name: "2-min Cold Shower",
    category: "recovery",
    weight: 1,
    emoji: "🚿",
  },

  // --- Mental & Social ---
  {
    id: "mindfulness-meditation",
    name: "10-min Mindfulness/Meditation",
    category: "mental",
    weight: 2,
    emoji: "🧠",
  },
  {
    id: "gratitude-journal",
    name: "5-min Gratitude Journal",
    category: "mental",
    weight: 1,
    emoji: "✍️",
  },
  {
    id: "read-a-book",
    name: "Read a Book for 30 min",
    category: "mental",
    weight: 2,
    emoji: "📖",
  },
  {
    id: "social-night-in",
    name: "Alcohol-Free Social Night",
    category: "social",
    weight: 3,
    emoji: "🤝",
  },
  {
    id: "less-screen-time",
    name: "Tech-Free Evening",
    category: "mental",
    weight: 2,
    emoji: "📱",
  },
  {
    id: "sunlight-exposure",
    name: "15-min Sunlight Exposure",
    category: "mental",
    weight: 2,
    emoji: "☀️",
  },
  {
    id: "put-phone-away",
    name: "Put Phone Away for 1 hr",
    category: "mental",
    weight: 2,
    emoji: "📵",
  },
  {
    id: "engage-in-hobby",
    name: "Engage in a Hobby",
    category: "mental",
    weight: 2,
    emoji: "🎨",
  },
  {
    id: "create-budget-plan",
    name: "Create a Budget Plan",
    category: "mental",
    weight: 3,
    emoji: "💰",
  },
  {
    id: "declutter",
    name: "Do a Declutter Session",
    category: "mental",
    weight: 2,
    emoji: "🧹",
  },
  {
    id: "pomodoro-technique",
    name: "Use Pomodoro Technique",
    category: "mental",
    weight: 1,
    emoji: "📋",
  },
  {
    id: "break-walk",
    name: "Take a 10-min Walk",
    category: "mental",
    weight: 1,
    emoji: "🚶",
  },
];
